steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "PAT=${_PAT}",
        "-t",
        "gcr.io/$PROJECT_ID/backend-orchestration",
        "./backend/orchestration"
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend-orchestration"]
